---
# - name: copy hosts
#   copy: src="hosts" dest="/etc/hosts" force=yes

- name: strict host key checking no
  blockinfile:
    dest: /etc/ssh/ssh_config
    block: |
       StrictHostKeyChecking no
  tags:
    - common     

- name: copy sources.list
  copy: src="sources.list" dest="/etc/apt/" force=yes
  tags:
    - common     


- apt: update_cache=yes cache_valid_time=72000
  ignore_errors: yes
  tags:
    - common     



- name: add /sbin to path
  lineinfile: dest="/etc/profile" line="PATH=/sbin/:$PATH"
  tags:
    - common     


# - name: disable ufw
#   ufw: state='disabled'

- name: remove iptables
  apt: name="iptables" state="absent"
  tags:
    - common     



- name: update host
  blockinfile:
    backup: yes
    dest: "/etc/hosts"
    block: |
      {{ hosts }}
  tags:
    - common     



- name: install softwares
  apt: name={{item}} state=present allow_unauthenticated=yes
  with_items:
    - wget
    - unzip
    - openssh-server
  tags:
    - common     


