---
# tasks file for zabbix3_2
- name: Create zabbix user group
  become: yes
  group: name={{zabbix_group}} state=present
  tags:
    - zabbix3

- name: Create zabbix user
  become: yes
  user:
    name: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
    system: true
  tags:
    - zabbix3

- name: Install zabbixrequired system packages.
  become: yes
  apt: pkg={{ item }} state=installed update_cache=true
  when: zabbixType == "server"
  with_items: "{{ zabbixserver_packages }}"
  tags:
    - zabbix3

- name: Download zabbix
  get_url: url="http://liquidtelecom.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/{{zabbix_version}}/zabbix-{{zabbix_version}}.tar.gz" dest="/home/{{ zabbix_user }}/zabbix-{{zabbix_version}}.tar.gz" mode=0440
  register: zabbix_download
  tags:
    - zabbix3

- name: create log dir
  file:
    path: "{{zabbix_log_dir}}"
    state: directory
    mode: 0660
    owner: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
  tags:
    - zabbix3

- stat: path="{{zabbix_tar_exact_path}}.tar.gz"
  register: zabbix_tar_stat
  tags:
    - zabbix3


- stat: path="{{zabbix_tar_exact_path}}"
  register: zabbix_extract_stat
  tags:
    - zabbix3

- name:  Extract zabbix  tar
  when:  zabbix_tar_stat.stat.exists == True and zabbix_extract_stat.stat.exists == False
  unarchive: src="{{zabbix_tar_exact_path}}.tar.gz" dest=/home/{{ zabbix_user }}/ copy=no owner={{ zabbix_user }} group={{ zabbix_group }}
  tags:
    - zabbix3

- stat: path={{zabbix_tar_exact_path}}/Makefile
  register: makefile_stat
  tags:
    - zabbix3

- name: Configure Make install
  register: config_makefile
  #when: makefile_stat.stat.exists == False
  shell: "./configure  --prefix={{zabbix_home}} --enable-server --enable-web --with-net-snmp --with-libcurl --with-libcurl2 --with-ssh2 --with-unixodbc --with-mysql"
  when: zabbixType == "server"
  args:
    chdir: "{{zabbix_tar_exact_path}}/"
  tags:
    - zabbix3

- name: Configure Make install
  register: config_makefile
  #when: makefile_stat.stat.exists == False
  shell: "./configure --enable-agent --prefix={{zabbix_home}}"
  when: zabbixType == "agent"
  args:
    chdir: "{{zabbix_tar_exact_path}}/"
  tags:
    - zabbix3

- name: Make install
  become: yes
  shell: make install
  args:
    chdir: "{{zabbix_tar_exact_path}}/"
  tags:
    - zabbix3

- name: check if mysql db already exists
  shell: "mysql -u{{zabbix_mysql_username}} -p{{ zabbix_mysql_password }} -e 'SHOW DATABASES;' | grep {{ zabbix_mysql_dbname }}"
  ignore_errors: yes
  register: server_dbstatus
  tags:
    - zabbix3


- name: create mysql database
  mysql_db: name={{ zabbix_mysql_dbname }} state=present
  when: server_dbstatus.rc != 0
  when: zabbixType == "server"
  tags:
    - zabbix3


- name: create mysql user
  mysql_user: name={{ zabbix_mysql_username }} password={{ zabbix_mysql_password }} priv={{ zabbix_mysql_dbname }}.*:ALL state=present
  no_log: true
  when: zabbixType == "server"
  tags:
    - zabbix3

- name: import mysql schema table
  mysql_db: name={{ zabbix_mysql_dbname }} state=import target={{zabbix_tar_exact_path}}/database/mysql/schema.sql
  when: server_dbstatus.rc != 0 and zabbixType == "server"
  # no_log: true
  tags:
    - zabbix3

- name: import mysql images table
  mysql_db: name={{ zabbix_mysql_dbname }} state=import target={{zabbix_tar_exact_path}}/database/mysql/images.sql
  when: server_dbstatus.rc != 0 and zabbixType == "server"
  # no_log: true
  tags:
    - zabbix3

- name: import mysql data table
  mysql_db: name={{ zabbix_mysql_dbname }} state=import target={{zabbix_tar_exact_path}}/database/mysql/data.sql
  when: server_dbstatus.rc != 0 and zabbixType == "server"
  no_log: true
  tags:
    - zabbix3

- name: copy zabbix php
  shell: "cp -r {{zabbix_tar_exact_path}}/frontends/php/ {{zabbix_frontends_path}}"
  become: yes

- name: set owner
  file:
    path: "{{zabbix_frontends_path}}"
    recurse: true
    owner: "root"
    group: "root"
    mode: "ug=rwx,o=rw"
  tags:
    - zabbix3


# - name: restart zabbix server
