---
- hosts: spark_slaves,spark_master
  become: yes
  vars_files:
    - ./vars/base-env.yml
  vars:
    isUseWordcountFile: "true"
  tasks:
    - name: delete jars
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "{{ wordcount_dependencies_folder }}/"
        - "{{ spark_home }}/{{app_name}}.jar"

    - name: create  dependency jars directory
      file:
        path: "{{wordcount_dependencies_folder}}"
        state: directory
        owner: "{{ spark_user }}"
        group: "{{ spark_group }}"

    - name: copy dependency jar to spark
      copy:
        src: "{{spark_app_with_dependencies_path}}"
        dest: "{{wordcount_dependencies_folder}}"
        owner: "{{spark_user}}"
        group: "{{spark_group}}"
        force: true

    - name: copy jar to spark
      copy:
        src: "{{spark_app_path}}"
        dest: "{{spark_home}}/"
        owner: "{{spark_user}}"
        group: "{{spark_group}}"
        force: true

- hosts: spark_slave1
  become: yes
  vars_files:
    - ./vars/base-env.yml
  tasks:
    - name: find jars
      find:
        paths: "{{wordcount_dependencies_folder}}/"
        patterns: "*.jar"
      register: jars

    - name: app's depenency
      debug:
        msg: "{{ jars.files | map(attribute='path') | join(',') }}"

    - name: submit "{{ip}}"
      become: true
      become_user: "{{spark_user}}"
      shell: "{{spark_home}}/bin/spark-submit --class {{app_main_class}} --master {{spark_master_host_port}} --deploy-mode cluster --jars {{ jars.files | map(attribute='path') | join(',') }} --executor-memory 1G --driver-memory 1G --executor-cores 1 file://{{spark_home}}/{{app_name}}.jar -name wordcount"
